task50-product-splash
odevpl/wdp2403 pull request #31
Opened 2024-04-04 12:50 UTC by stelmonitos

task nie jest jeszcze ukonczony mam problem ze po naniesieniu zmian scroll na stronie nie dziala oraz znikaja filtry

2024-04-06 15:50 UTC, wjozwik requested changes
![image](https://github.com/odevpl/wdp2403/assets/151070071/7d96855b-ff1d-4c38-994b-4c7954d981f5)
![image](https://github.com/odevpl/wdp2403/assets/151070071/ce6b1414-78d5-455f-a99d-a676603ef3b9)
dalej jest problem z filtrami. diva wrzuca na dole strony dlatego go nie widzisz

2024-04-07 07:23 UTC, stelmonitos commented
powinno byc gotowe do zmergowania

2024-04-07 11:22 UTC, wjozwik requested changes
powinnismy uzywac kolorow dostarczonych w settings.scss. 
![image](https://github.com/odevpl/wdp2403/assets/151070071/4eef7694-5173-4947-bacd-f2c30506bba2)

Przypisywac je do zmiennych (np mozesz stworzyc nowa sekcje stylow) i dopiero te zmienne uzywac w komponentach. Popraw to prosze i mergujemy.
![image](https://github.com/odevpl/wdp2403/assets/151070071/8575690a-417f-43a7-bcd7-0999585bb759)

2024-04-08 10:56 UTC, stelmonitos commented
done

2024-04-08 15:25 UTC, wjozwik approved these changes

2024-04-08 15:25 UTC, merged