Task 66 subpage favorite products
odevpl/wdp2403 pull request #40
Opened 2024-04-08 12:50 UTC by stelmonitos

Twoim zadaniem jest dodanie nowej podstrony, na której wyświetlą się wszystkie produkty dodane do ulubionych. Możesz skorzystać z komponentu używanego w NewFurniture

2024-04-08 17:33 UTC, slawomirtoporek requested changes
Co myślisz o tym, żeby liczbę kolumn dostosować do tego, ile wyświetlanych jest kolumn w innych zakładkach?

2024-04-08 18:12 UTC, stelmonitos commented
zrobione

2024-04-08 19:27 UTC, slawomirtoporek requested changes
chodzi mi konkretnie o to żeby wygląd podstrony favorite, był spójny z resztą podstron i miał 4 kolumny w rzędzie na desktopie. 
![image](https://github.com/odevpl/wdp2403/assets/54867086/cbf83aaf-7346-459a-ae08-5ee1e8042b02)

2024-04-08 20:56 UTC, stelmonitos commented
w sensie na desktopie ma 4 w rzedzie, probuje zrobic, a nie moge dodac komponentu furniture do favorite bo sa rozne categorie a na podstawie tego dawana jest nazwa w navbarze chyba ze cos przeoczylem, musialbym w initialState stworzyc nowa kategorie

2024-04-08 22:59 UTC, slawomirtoporek commented
wystarczy że skorzystasz z hooku useContext, tak jak w komponencie Furniture. To createContext, przekazuje globalnie z komponentu MainLayout ilosc kolumn, a hook useContext te dane odbiera.
![image](https://github.com/odevpl/wdp2403/assets/54867086/c6328617-1c91-40d1-a4a4-a15b1d5bcbc3).  Jak cos to napisz, to ogarniemy to jutro razem.

2024-04-09 06:52 UTC, stelmonitos commented
jasne, sprobuje sam i jak cos dam znac na komunikatorze

2024-04-09 07:04 UTC, stelmonitos commented
zostalo mi jedynie do poprawy teraz to:
![image](https://github.com/odevpl/wdp2403/assets/148702992/4bffc183-1fa9-4ca9-83c2-0fb2b6e887f6)

2024-04-09 09:49 UTC, slawomirtoporek approved these changes
super :)

2024-04-09 09:50 UTC, merged