task 41
odevpl/wdp2403 pull request #7
Opened 2024-03-22 23:56 UTC by luqol

RWD dla menu głównego (wyszukiwanie i "Home", etc.)

2024-03-25 13:33 UTC, luqol commented
konflikty rozwiazane

2024-03-27 10:32 UTC, luqol commented
Adjusted RWD for extra small width

2024-03-28 09:00 UTC, luqol commented
konflikty rozwiązane

2024-04-01 22:06 UTC, slawomirtoporek requested changes
Zerknij proszę, na szerokość 768px, burger jest po lewej stronie, a menu po prawej stronie.

2024-04-02 09:56 UTC, luqol commented
naprawiony problem na szerokości 768 px

2024-04-02 19:17 UTC, slawomirtoporek approved these changes
teraz wszystko w porządku :)

2024-04-02 19:17 UTC, merged